name: Build and Publish accounts-ui Docker Image

on:
  push:
    branches:
      - main
    # paths:
    #   - 'accounts-ui/**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./accounts-ui
          file: ./accounts-ui/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/accounts-ui:latest
