name: Build and Publish Service Docker Image

on:
  push:
    branches: [ "main" ]
    paths: [ "state-service/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd state-service
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/state-service:latest
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image with latest tag
      run: docker push ghcr.io/${{ github.repository }}/state-service:latest
